### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by saniales** [JohanDuque/crypto-trader#9]
Is it possible to have a documentation of the code?
From what I see:
- README is incomplete
- Wiki is missing
- code is not documented (jsdoc)

Without these I find really hard to understand the code, except for the clean code structure which helps me a bit

I really hope to see this ;)

**Comment by JohanDuque** [comment]
Sure, it is possible to have the documentation, what you see is right, I'm missing README and Wiki.
Feel free to branch and start both **README** and **Wiki**, propose the sections you would like to see, then we can fill them together. 
If worths your time to write the docs, worths mine to share the knowledge :)
Personally, I don't care about *jsdoc* they just add noise to a clean code base, but again, feel free to branch and integrate them.

**Comment by saniales** [comment]
If you create a decent README I can consider the idea to put my effort in creating a cool wiki :)

**Comment by JohanDuque** [comment]
This is how it works: 
- If you need help, you **kindly** ask for it.
- If you want something done, **you just do it** and then make a pull request.
